#ifndef CONFIG_HPP_DEPISTAGE
#define CONFIG_HPP_DEPISTAGE

#define DEPISTAGE_MAJOR 1
#define DEPISTAGE_MINOR 0
#define DEPISTAGE_PATCH 0
#define DEPISTAGE_RELEASE 02/03/2014

#endif // CONFIG_HPP_DEPISTAGE
