#ifndef CONFIG_HPP_DEPISTAGE
#define CONFIG_HPP_DEPISTAGE

#define DEPISTAGE_MAJOR 0
#define DEPISTAGE_MINOR 0
#define DEPISTAGE_PATCH 0
#define DEPISTAGE_RELEASE 12/12/2013

#endif // CONFIG_HPP_DEPISTAGE
