#ifndef CONFIG_HPP_DEPISTAGE
#define CONFIG_HPP_DEPISTAGE

#define DEPISTAGE_MAJOR 2
#define DEPISTAGE_MINOR 0
#define DEPISTAGE_PATCH 0
#define DEPISTAGE_RELEASE 27/08/2014

#endif // CONFIG_HPP_DEPISTAGE
