#ifndef CONFIG_HPP_DEPISTAGE
#define CONFIG_HPP_DEPISTAGE

#define DEPISTAGE_MAJOR @DEPISTAGE_MAJOR@
#define DEPISTAGE_MINOR @DEPISTAGE_MINOR@
#define DEPISTAGE_PATCH @DEPISTAGE_PATCH@
#define DEPISTAGE_RELEASE @DEPISTAGE_RELEASE@

#endif // CONFIG_HPP_DEPISTAGE
